### ISSUE TITLE
Cbr & CBZ are now unreadable

### ISSUE THREAD

**Issue by lb1blink** [xthursdayx/yacreaderlibrary-server-docker#4]
After the update my server can open PDFs but CBR & CBZ give “timeout Error. Unable to connect to YACReader”

I am running UnRAID 6.9.2 and tried also updaying my library and removing re-adding.

**Comment by xthursdayx** [comment]
Hey, when did you last pull the image? I've spent the two days working on repackaging the image with a more stable compression backend, so you may have an unintentionally broken pull. I just checked the code and I think I see what the issue is. I'm pushing another build right now, so it should be up on Docker Hub in like 15 mins or so. Try pulling it again in a bit and let me know if you're still running into any issues.

**Comment by xthursdayx** [comment]
Just FYI, I'll likely be merging my testing branch into the main branch sometime today or tomorrow, which should be the most stable and streamlined version of this container.

**Comment by xthursdayx** [comment]
The new `latest` image is up now on Docker Hub and I just tested it and it's working with .cbr and .cbz files. Please update your container when you have chance. Sorry for the hiccup. Cheers!

**Comment by lb1blink** [comment]
It works perfectly now! You are amazing and so quick, thank you 1 million times over!

Rick

**Comment by lb1blink** [comment]
It works perfectly now! You are amazing and so quick, thank you 1 million times over!

**Comment by xthursdayx** [comment]
No worries, glad it's working for you. Be on the lookout for the next major update. I'll probably separate them by tags so you can choose to either go with the unarr or p7zip backend and will explain the benefits of each in the documentation.
